version: '3'

services:
  webserver:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html

  phpfpm:
    image: sportesi/figuredtest:latest
    working_dir: /usr/share/nginx/html/
    volumes:
      - ./:/usr/share/nginx/html/
  
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  postgresql:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=figuredtest

  redis:
    image: redis:5-alpine

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025